name: Lint rq

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4.6.1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black ruff

    - name: Check formatting with black
      run: |
        black --check --skip-string-normalization --line-length 120 src/rq tests

    - name: Check lint with ruff
      run: |
        # stop the build if there are Python syntax errors.
        ruff check --show-source src/rq tests
